"use strict";
(async()=>{
  let f;
  if(typeof module==="object"&&module.exports) f=require("../web/features.js");
  else { await import("../web/features.js"); f=globalThis.MamalotyFeatures; }
  const assert=(condition,message="assertion failed")=>{if(!condition)throw new Error(message);};
  const equal=(actual,expected)=>assert(actual===expected,`${actual} !== ${expected}`);
  const receiver={lat:0,lon:0};
  assert(Math.abs(f.bearing(0,0,1,0)-0)<1e-9);
  assert(Math.abs(f.bearing(0,0,0,1)-90)<1e-9);
  equal(f.cardinal(225),"SW");
  const look=f.look(receiver,{lat:0,lon:0.089932,alt_geom:32808.4},100,10);
  assert(Math.abs(look.distanceKm-10)<0.03);
  assert(Math.abs(look.elevation-44.68)<0.15);
  equal(look.cardinal,"E");
  equal(f.badges({mlat:["lat","lon"]})[0][0],"MLAT");
  assert(f.badges({wakeCategory:"H"}).some(x=>x[0]==="HEAVY"));
  assert(f.badges({typeDesc:"H2T"}).some(x=>x[0]==="HELIKOPTER"));
  for(const aircraft of [{emergency:"general"},{squawk:"7500"},{squawk:"7600"},{squawk:"7700"}]) assert(f.emergency(aircraft));
  assert(!f.emergency({emergency:"none",squawk:"1234"}));
  const visualFixtures={R44:"helicopter",F16:"fighter",C130:"military-transport",C172:"light-prop",AT72:"turboprop",GLF5:"business-jet",E190:"narrowbody",B738:"narrowbody",B77W:"widebody",A388:"super-heavy"};
  for(const [type,expected] of Object.entries(visualFixtures))equal(f.aircraftVisualClass({t:type}),expected);
  const memory={value:null,writes:0,getItem(){return this.value;},setItem(_,v){this.value=v;this.writes++;}};
  let stats=f.emptyDaily(new Date(2026,7,8));
  stats=f.updateDaily(stats,[{hex:"abc123",lat:0,lon:1,seen:0,seen_pos:0,alt_baro:10000,messages:10,rssi:-20,mlat:["lat","lon"]}],receiver,new Date(2026,7,8,0,0,0));
  equal(Object.keys(stats.seen).length,1); equal(Object.keys(stats.mlat).length,1); equal(Object.keys(stats.needsMlat).length,1);
  assert(!stats.highest,"one altitude sample must not set a record");
  stats=f.updateDaily(stats,[{hex:"abc123",seen:0,alt_baro:10050,messages:11}],receiver,new Date(2026,7,8,0,0,3));
  assert(!stats.highest,"two altitude samples must not set a record");
  stats=f.updateDaily(stats,[{hex:"abc123",seen:0,alt_baro:9950,messages:12}],receiver,new Date(2026,7,8,0,0,6));
  equal(stats.highest.value,9950);
  stats=f.updateDaily(stats,[{hex:"bad999",lat:0,lon:2,seen:0,seen_pos:0,alt_baro:119100,messages:1}],receiver,new Date(2026,7,8,0,0,7));
  equal(stats.highest.value,9950);
  stats=f.updateDaily(stats,[{hex:"def456",seen:1}],receiver,new Date(2026,7,8)); equal(Object.keys(stats.needsMlat).length,2);
  stats=f.updateDaily(stats,[{hex:"def456",lat:1,lon:1,seen_pos:1}],receiver,new Date(2026,7,8)); equal(Object.keys(stats.needsMlat).length,1); assert(stats.directPosition.def456);
  assert(f.checkpoint(stats,memory,1000000)); assert(!f.checkpoint(stats,memory,1000001)); equal(memory.writes,1);
  const restored=f.restoreDaily(memory,new Date(2026,7,8)); assert(restored.seen.abc123);
  const legacy={value:JSON.stringify({day:"2026-08-08",seen:{abc123:1},mlat:{abc123:1}}),getItem(){return this.value;}};
  const migrated=f.restoreDaily(legacy,new Date(2026,7,8)); assert(migrated.needsMlat.abc123);
  assert(!migrated.highest,"legacy unconfirmed altitude records must be discarded");
  const bounds={south:0,north:10,west:0,east:10};
  assert(f.inViewport(bounds,{lat:5,lon:5}));
  assert(f.inViewport(bounds,{lat:11,lon:5},.15));
  assert(!f.inViewport(bounds,{lat:12,lon:5},.15));
  assert(!f.trailDirty([1,2],{lat:1.00001,lon:2.00001}));
  assert(f.trailDirty([1,2],{lat:1.001,lon:2}));
  const coalesced=f.coalesceRequest({force:false,priority:"OLD"},{force:true,priority:null});
  assert(coalesced.force);equal(coalesced.priority,"OLD");
  equal(f.nearestAircraftHit([{hex:"a",x:10,y:10},{hex:"b",x:30,y:30}],{x:27,y:28},8).hex,"b");
  assert(!f.nearestAircraftHit([{hex:"a",x:10,y:10}],{x:30,y:30},8));
  const reset=f.updateDaily(restored,[],receiver,new Date(2026,7,9)); equal(Object.keys(reset.seen).length,0);
  console.log("Feature tests passed");
})().catch(error=>{console.error(error); if(typeof process!=="undefined")process.exitCode=1; else Deno.exit(1);});
