#!/usr/bin/env python3
"""Validate master SVGs and generate the browser's embedded icon table."""
import argparse
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "web/icons/aircraft"
OUTPUT = ROOT / "web/generated-aircraft-icons.js"
EXPECTED = (
    "helicopter", "fighter", "military-transport", "light-prop", "turboprop",
    "business-jet", "narrowbody", "widebody", "super-heavy",
)

def generate():
    icons = {}
    files = {path.stem: path for path in SOURCE.glob("*.svg")}
    if set(files) != set(EXPECTED):
        missing = sorted(set(EXPECTED) - set(files))
        extra = sorted(set(files) - set(EXPECTED))
        raise ValueError(f"icon set mismatch; missing={missing}, extra={extra}")
    for name in EXPECTED:
        root = ET.parse(files[name]).getroot()
        if root.tag.rsplit("}", 1)[-1] != "svg" or root.get("viewBox") != "0 0 32 32":
            raise ValueError(f"{name}.svg must use viewBox=\"0 0 32 32\"")
        paths = [node for node in root.iter() if node.tag.rsplit("}", 1)[-1] == "path"]
        if len(paths) != 1 or paths[0].get("fill") != "currentColor" or not paths[0].get("d"):
            raise ValueError(f"{name}.svg must contain one currentColor path")
        if any(node.tag.rsplit("}", 1)[-1] not in {"svg", "path"} for node in root.iter()):
            raise ValueError(f"{name}.svg contains unsupported elements")
        icons[name] = paths[0].get("d")
    rows = ",\n".join(f"    {json.dumps(name)}: {json.dumps(icons[name])}" for name in EXPECTED)
    return "// Generated by scripts/build-aircraft-icons.py; edit web/icons/aircraft/*.svg.\n" + \
           "window.MamalotyAircraftIcons = Object.freeze({\n" + rows + "\n});\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()
    try:
        content = generate()
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
                print(f"Stale generated file: {OUTPUT}", file=sys.stderr)
                return 1
        else:
            OUTPUT.write_text(content, encoding="utf-8")
            print(f"Generated {OUTPUT.relative_to(ROOT)}")
    except (ET.ParseError, OSError, ValueError) as error:
        print(f"Aircraft icon build failed: {error}", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
